n_neighbors: 20
contamination: 0.09
min_tgt_corr: 0.001
max_mutual_corr: 0.9
n_estimators: 100
max_depth: 6
learning_rate: 0.3
gamma: 0.0
min_child_weight: 1.0
subsample: 1.0
colsample_bytree: 1.0
reg_lambda: 1.0
